GRANT USAGE ON * . * TO 'trial'@'localhost' IDENTIFIED BY 'trial' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;

CREATE DATABASE `doit` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON `doit` . * TO 'trial'@'localhost' WITH GRANT OPTION;
